"""Write the whole answer bank out as one readable document.

    python3 tools/export-bank.py > CROSSWORD-BANK.md

**Two different things get counted here and they are not the same size.** The
*fill pool* is every word the generator may put in a grid — 10,395 of them,
most carrying a clue derived from a WordNet gloss. The *clue table* is the
subset somebody has hand-written a clue for, which is 1,501.

The gap is not a gap in the pool, and the earlier version of this document
implied it was: it listed only the hand-written table under the heading "every
answer the app can use", so the sevens, eights and nines looked almost empty —
52, 3 and 1 — when the pool actually holds 2,277, 1,172 and 868 of them. A clue
only gets hand-written once an answer lands in a shipped puzzle, and long
entries rarely do, because bars cut most lines into pieces of three to six.

Three sources, and the document keeps them apart because they are governed by
different rules:

  * tools/cross-clues.py   — dictionary words, the pool that fills 5/7/9
  * tools/extra-answers.py — abbreviations, brands and names, deliberately
                             outside the Scrabble dictionary
  * tools/cross-phrases.py — the 15x15 pool: run-together phrases and people

Usage counts come from ~/bank.json, so an answer marked `unused` is clued and
available but has not yet landed in a shipped puzzle.
"""
import collections
import importlib.util
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load(name, attr):
    path = os.path.join(ROOT, 'tools', name)
    spec = importlib.util.spec_from_file_location('m_' + attr, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return getattr(mod, attr)


def clue_list(v):
    return [v] if isinstance(v, str) else list(v)


def table(out, items, use, show_use=True):
    """One row per answer: the word, its length, and every clue it carries."""
    out.append('| Answer | Len | Clue |')
    out.append('|---|---|---|')
    for ans, v in items:
        cs = clue_list(v)
        tag = ''
        if show_use:
            n = use.get(ans, 0)
            tag = ' _(x%d)_' % n if n > 1 else ('' if n else ' _(unused)_')
        out.append('| **%s**%s | %d | %s |'
                   % (ans.upper(), tag, len(ans), '<br>'.join(cs)))
    out.append('')


def fill_pool():
    """Every word the generator may use, via rebuild-bank.word_bank()."""
    try:
        spec = importlib.util.spec_from_file_location(
            'rb_pool', os.path.join(ROOT, 'tools', 'rebuild-bank.py'))
        rb = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(rb)
        return rb.word_bank(rb._load('build-crosswords'))
    except Exception:
        return {}


def main():
    CLUES = _load('cross-clues.py', 'CLUES')
    EXTRA = _load('extra-answers.py', 'EXTRA')
    PHRASES = _load('cross-phrases.py', 'PHRASES')
    PEOPLE = _load('cross-phrases.py', 'PEOPLE')

    use = collections.Counter()
    bankpath = os.path.expanduser('~/bank.json')
    if os.path.exists(bankpath):
        bank = json.load(open(bankpath))
        for size in bank:
            for p in bank[size]:
                for a in p['answers']:
                    use[a] += 1

    words_only = {k: v for k, v in CLUES.items() if k not in EXTRA}
    n_clues = sum(len(clue_list(v)) for v in CLUES.values())
    n_new = sum(len(clue_list(v)) for v in
                list(PHRASES.values()) + list(PEOPLE.values()))

    out = []
    out.append('# Focus Simulator — the crossword answer bank')
    out.append('')
    out.append('Every answer the app can use, next to the clue it carries. '
               'Generated by `tools/export-bank.py`.')
    out.append('')
    out.append('| Pool | Answers | Clues | Lengths |')
    out.append('|---|---|---|---|')

    def spread(d):
        ls = sorted(len(k) for k in d)
        return '%d-%d' % (ls[0], ls[-1])

    out.append('| Dictionary words (`cross-clues.py`) | %d | %d | %s |'
               % (len(words_only), n_clues, spread(words_only)))
    out.append('| Abbreviations, brands, names (`extra-answers.py`) | %d | %d | %s |'
               % (len(EXTRA), len(EXTRA), spread(EXTRA)))
    out.append('| **NEW** phrases (`cross-phrases.py`) | %d | %d | %s |'
               % (len(PHRASES), len(PHRASES), spread(PHRASES)))
    out.append('| **NEW** people (`cross-phrases.py`) | %d | %d | %s |'
               % (len(PEOPLE), sum(len(clue_list(v)) for v in PEOPLE.values()),
                  spread(PEOPLE)))
    out.append('')
    out.append('**Total: %d answers, %d clues.**'
               % (len(words_only) + len(EXTRA) + len(PHRASES) + len(PEOPLE),
                  n_clues + len(EXTRA) + n_new))
    out.append('')
    pool = fill_pool()
    if pool:
        pc = collections.Counter(len(w) for w in pool)
        hc = collections.Counter(len(w) for w in CLUES)
        out.append('')
        out.append('## What the generator can actually reach for')
        out.append('')
        out.append('The tables further down list the **hand-written clue '
                   'table**. That is a subset. A clue is only written by hand '
                   'once an answer lands in a shipped puzzle, and long entries '
                   'rarely do — bars cut most lines into pieces of three to '
                   'six — so the sevens, eights and nines look bare below while '
                   'the pool holds thousands of them.')
        out.append('')
        out.append('| Length | In the fill pool | Hand-written clue |')
        out.append('|---|---|---|')
        for L in range(3, 16):
            if pc[L] or hc[L]:
                out.append('| %d | %d | %d |' % (L, pc[L], hc[L]))
        out.append('| **total** | **%d** | **%d** |' % (len(pool), len(CLUES)))
        out.append('')
        out.append('Anything in the pool without a hand-written clue ships with '
                   'a clue trimmed from its WordNet definition, which is why '
                   '`rebuild-bank.py --clues` exists: it lists exactly those, '
                   'and they are what to rewrite next.')
        out.append('')
        out.append('---')
        out.append('')
    out.append('`(x3)` means the answer is in three shipped puzzles. '
               '`(unused)` means it is clued and ready but has not landed in a '
               'grid yet. Answers with two clues show both, one per line; '
               '`crossClue` picks between them by puzzle index so a given '
               'puzzle always shows the same one.')
    out.append('')
    out.append('---')
    out.append('')

    # ---- part 1: the new 15x15 pool ----
    out.append('## Part 1 — NEW: the 15x15 pool')
    out.append('')
    out.append('Nothing in this part is wired into the app yet. It exists '
               'because the current bank has only three answers of eight '
               'letters or more, and a 15x15 needs long entries in every '
               'corner.')
    out.append('')
    out.append('### Phrases, spaces removed')
    out.append('')
    bylen = collections.defaultdict(list)
    for k, v in PHRASES.items():
        bylen[len(k)].append((k, v))
    for L in sorted(bylen):
        out.append('#### %d letters (%d)' % (L, len(bylen[L])))
        out.append('')
        table(out, sorted(bylen[L]), use, show_use=False)

    out.append('### People')
    out.append('')
    out.append('The name is never in its own clue. Where a first name is needed '
               'to pin down which person, it goes in the clue and the surname '
               'is the answer — so "Artist Steve who drew the first Spider-Man" '
               'wants DITKO.')
    out.append('')
    table(out, sorted(PEOPLE.items()), use, show_use=False)

    out.append('---')
    out.append('')

    # ---- part 2: what is already shipping ----
    out.append('## Part 2 — the bank as it ships today')
    out.append('')
    out.append('### Abbreviations, brands and names')
    out.append('')
    out.append('Deliberately outside the Scrabble dictionary. They exist '
               'because ordinary English is thin at three letters.')
    out.append('')
    table(out, sorted(EXTRA.items()), use)

    out.append('### Dictionary words')
    out.append('')
    bylen = collections.defaultdict(list)
    for k, v in words_only.items():
        bylen[len(k)].append((k, v))
    for L in sorted(bylen):
        out.append('#### %d letters (%d)' % (L, len(bylen[L])))
        out.append('')
        table(out, sorted(bylen[L]), use)

    sys.stdout.write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
