<#
  One command from source to the phone in your hand.

      npm run phone            build, sync, compile, install, launch
      npm run phone -- -ApkOnly    stop after the APK and print where it is
      npm run phone -- -NoLaunch   install but do not open it

  **Why this exists.** Getting a change onto the phone is five steps and the one
  people skip is `cap sync` — which does not fail, it just installs the old web
  build, so the change appears not to have worked. That is the same trap as
  running the app from the Start menu instead of `start.cmd` (HANDOFF §4), and
  it costs the same afternoon. This does all five in order, every time.

  **The JDK is the thing that goes wrong.** `android/` is generated by Capacitor
  and its Gradle wrapper is pinned at 8.2.1, which cannot run under a JDK newer
  than 20 — it dies with "Unsupported class file major version" while evaluating
  a settings script, which reads like a broken project rather than a wrong Java.
  Android Studio ships a JBR that is far newer than that, so the obvious
  JAVA_HOME is the one that does not work. This looks for a usable one, says so
  plainly when there is none, and never guesses.
#>
[CmdletBinding()]
param(
  [switch]$ApkOnly,      # build the APK and stop
  [switch]$NoLaunch,     # install, but do not start it
  [switch]$SkipBuild,    # the web build and cap sync are already done
  [string]$Jdk = ''      # a JDK to use, overriding everything below
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

function Say([string]$m) { Write-Host "  $m" -ForegroundColor Cyan }
function Warn([string]$m) { Write-Host "  $m" -ForegroundColor Yellow }
function Die([string[]]$m) {
  Write-Host ''
  foreach ($line in $m) { Write-Host "  $line" -ForegroundColor Red }
  exit 1
}

# ---- the JDK ---------------------------------------------------------------
# Gradle 8.2.x runs on Java 8 to 20. Anything newer fails in the Groovy
# compiler, and the message names a settings file rather than the Java.
$JDK_MAX = 20

# **Read the release file; do not run java to ask.** Every JDK has one, and it
# says JAVA_VERSION="17.0.14". Running java -version was the first way this
# asked, and it never once worked: java prints its version to stderr, Windows
# PowerShell turns each stderr line of a native program into an error record
# under 2>&1, and with $ErrorActionPreference = 'Stop' set above that record
# throws - so the catch returned 0 for every JDK on the machine, including the
# Temurin the error message tells you to install. Running java is kept only
# as a fallback, with errors allowed for the length of the call.
function JavaMajor([string]$jdkHome) {
  $exe = Join-Path $jdkHome 'bin\java.exe'
  if (-not (Test-Path $exe)) { return 0 }
  $release = Join-Path $jdkHome 'release'
  if (Test-Path $release) {
    $text = Get-Content $release -Raw -ErrorAction SilentlyContinue
    if ($text -match 'JAVA_VERSION="1\.(\d+)') { return [int]$Matches[1] }
    if ($text -match 'JAVA_VERSION="(\d+)') { return [int]$Matches[1] }
  }
  $was = $ErrorActionPreference
  try {
    $ErrorActionPreference = 'Continue'
    $out = cmd /c "`"$exe`" -version 2>&1" | Out-String
    if ($out -match 'version "1\.(\d+)') { return [int]$Matches[1] }
    if ($out -match '"(\d+)') { return [int]$Matches[1] }
  } catch {
  } finally {
    $ErrorActionPreference = $was
  }
  return 0
}

function FindJdk {
  $tries = @()
  if ($Jdk) { $tries += $Jdk }
  if ($env:FOCUS_JDK) { $tries += $env:FOCUS_JDK }
  if ($env:JAVA_HOME) { $tries += $env:JAVA_HOME }
  foreach ($base in @(
      'C:\Program Files\Eclipse Adoptium',
      'C:\Program Files\Java',
      'C:\Program Files\Microsoft\jdk',
      'C:\Program Files\Amazon Corretto',
      'C:\Program Files\Zulu',
      "$env:LOCALAPPDATA\Programs\Eclipse Adoptium",
      # Where IntelliJ and Android Studio keep a JDK they downloaded, and where
      # Gradle keeps the ones it provisions. This machine had a working Java 17
      # in the first of these all along, and the script told you to install
      # one because it never looked there.
      "$env:USERPROFILE\.jdks",
      "$env:USERPROFILE\.gradle\jdks")) {
    if (Test-Path $base) {
      $tries += (Get-ChildItem $base -Directory -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName })
    }
  }
  # Last, because it is usually far too new to be any use here — but if it is
  # the only Java on the machine it is worth naming in the error.
  $tries += 'C:\Program Files\Android\Android Studio\jbr'

  $seen = @()
  foreach ($t in $tries) {
    if (-not $t -or $seen -contains $t) { continue }
    $seen += $t
    $v = JavaMajor $t
    if ($v -gt 0 -and $v -le $JDK_MAX) { return @{ home = $t; ver = $v } }
    if ($v -gt 0) { Warn "Java $v at $t is too new for the Gradle in android/ (needs $JDK_MAX or older)" }
  }
  return $null
}

# **$java, not $jdk.** PowerShell variable names ignore case, so $jdk *is* the
# [string]$Jdk parameter above — and assigning the hashtable FindJdk returns to
# a string-typed parameter quietly stores the text "System.Collections.Hashtable".
# Its .home and .ver are then empty, JAVA_HOME is set to nothing, and Gradle
# says no Java was found right after this script said it found one.
$java = FindJdk
if (-not $java) {
  Die @(
    'No usable JDK.',
    '',
    'The Gradle wrapper in android/ is 8.2.1 and needs Java 17 (anything from 8',
    "to $JDK_MAX will do). Android Studio's bundled JBR is much newer than that,",
    'which is why the obvious JAVA_HOME is the one that does not work here.',
    '',
    '    winget install EclipseAdoptium.Temurin.17.JDK',
    '',
    'then either let this script find it, or point it at one:',
    '',
    '    npm run phone -- -Jdk "C:\Program Files\Eclipse Adoptium\jdk-17..."',
    '',
    'Or skip all of this and use Android Studio, which manages its own:',
    '',
    '    npm run android'
  )
}
$env:JAVA_HOME = $java.home
Say "Java $($java.ver) — $($java.home)"

# ---- adb -------------------------------------------------------------------
$adb = ''
foreach ($p in @(
    "$env:LOCALAPPDATA\Android\Sdk\platform-tools\adb.exe",
    "$env:ANDROID_HOME\platform-tools\adb.exe",
    "$env:ANDROID_SDK_ROOT\platform-tools\adb.exe")) {
  if ($p -and (Test-Path $p)) { $adb = $p; break }
}
if (-not $adb) { $c = Get-Command adb -ErrorAction SilentlyContinue; if ($c) { $adb = $c.Source } }

# ---- the web build, and the copy into the native project -------------------
# **This is the step that gets skipped**, and skipping it does not fail: the
# APK builds perfectly and contains last week's index.html.
if (-not $SkipBuild) {
  Say 'Building dist/…'
  & npm run build --silent
  if ($LASTEXITCODE -ne 0) { Die 'The web build failed.' }

  if (-not (Test-Path (Join-Path $root 'android'))) {
    Say 'No android/ yet — creating it (npx cap add android)…'
    & npx cap add android
    if ($LASTEXITCODE -ne 0) { Die 'cap add android failed.' }
  }

  Say 'Copying it into android/ (npx cap sync)…'
  & npx cap sync android
  if ($LASTEXITCODE -ne 0) { Die 'cap sync failed.' }
}

# ---- compile ---------------------------------------------------------------
Say 'Compiling the APK…'
Push-Location (Join-Path $root 'android')
try {
  & .\gradlew.bat :app:assembleDebug --console=plain -q
  $gradleCode = $LASTEXITCODE
} finally { Pop-Location }
if ($gradleCode -ne 0) { Die 'Gradle failed. Run it by hand for the full output: cd android; .\gradlew.bat :app:assembleDebug' }

$apk = Join-Path $root 'android\app\build\outputs\apk\debug\app-debug.apk'
if (-not (Test-Path $apk)) { Die "Gradle said it succeeded but there is no APK at $apk" }
$size = [math]::Round((Get-Item $apk).Length / 1MB, 1)
Say "APK: $apk  ($size MB)"

if ($ApkOnly) {
  Write-Host ''
  Write-Host '  Copy that to the phone and open it. Android will ask about installing' -ForegroundColor Green
  Write-Host '  from an unknown source; that is expected for a debug build.' -ForegroundColor Green
  exit 0
}

# ---- install ---------------------------------------------------------------
if (-not $adb) {
  Warn 'No adb, so nothing was installed. The APK path is above.'
  exit 0
}
$devices = (& $adb devices) | Select-Object -Skip 1 | Where-Object { $_ -match '\sdevice$' }
if (-not $devices) {
  Warn 'No phone attached. Plug it in with USB debugging on, accept the prompt on the'
  Warn 'phone, and run this again — or copy the APK across by hand.'
  exit 0
}
Say "Installing on $($devices.Count) device(s)…"
# -r keeps the data. Without it every install is a fresh app with an empty
# calendar, and the app's whole point is what it has written down.
& $adb install -r $apk
if ($LASTEXITCODE -ne 0) {
  Die @(
    'Install failed. The usual cause is a signature clash: a build signed with',
    'a different debug key cannot replace one already there.',
    '',
    'Uninstalling first fixes it and throws away everything on the phone, so',
    'export a backup from the menu before you do:',
    '',
    '    adb uninstall app.focussimulator.mobile'
  )
}

if (-not $NoLaunch) {
  Say 'Launching…'
  & $adb shell am start -n app.focussimulator.mobile/.MainActivity | Out-Null
}

Write-Host ''
Write-Host '  On the phone now.' -ForegroundColor Green
Write-Host '  Check the build stamp at the bottom of the menu against package.json.' -ForegroundColor Green
